src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Finish_datetime__c</fullName>
        <label>Finish datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_datetime__c</fullName>
        <label>Start datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Types of events occurring during the internship.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lesson</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge check</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation</fullName>
                <color>#E27001</color>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventBuilder.cls
public class EventBuilder{
	//private String Name;
	//private Datetime Finish_datetime__c; 

    public static Builder getEvent(){
        return new Builder();
    }

    public class Builder{
        private Event__c eventRecord;

        private Builder(){
            eventRecord = new Event__c();
        }

        public Builder save(){
            upsert eventRecord;
            return this;
        }

        public Builder setName(String Name){
            eventRecord.Name = Name;
            return this;
        }

		public Builder setStartDatetime(Datetime startDatetime){
            eventRecord.Start_datetime__c = startDatetime;
            return this;
        }

		public Builder setFinishDatetime(Datetime finishDatetime){
            eventRecord.Finish_datetime__c = finishDatetime;
            return this;
        }

		public Builder setTopic(String topic){
            eventRecord.Topic__c = topic;
            return this;
        }

		public Builder setTeacher(Id teacher){
            eventRecord.Teacher__c = teacher;
            return this;
        }

		public Builder setType(String type){
            eventRecord.Type__c = type;
            return this;
        }

        public Event__c getRecord(){
            return eventRecord;
        }

    }
}