src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE(Start_datetime__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finish_datetime__c</fullName>
        <label>Finish datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_datetime__c</fullName>
        <label>Start datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserAtTheEvent__c.object
<CustomObject>
    <fields>
        <fullName>EventId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EventId</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>UserAtTheEvent</relationshipLabel>
        <relationshipName>UserAtTheEvent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserId</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserAtTheEvent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserAtTheEvent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>UserAtTheEvent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserAtTheEvent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleController.cls
public class ScheduleController {
    public static List<Event__c> eventOfDayList {get; set;}
	public static List<WAttendance> wAttendanceList {get; set;}
	List<Event__c> allEventInDate;
    public ScheduleController(){
        scheduleMaker(Date.today().addDays(-1));
		makeVisitReport(Date.today().addDays(-1));
    }

    private static void scheduleMaker(Date currentDay){
        eventOfDayList = [SELECT Id, Name, Start_datetime__c, Finish_datetime__c, Teacher__r.Name, Topic__c FROM Event__c WHERE Date__c = :currentDay ORDER BY Start_datetime__c ASC];
    }
	

	private static void makeVisitReport(Date currentDay){
		wAttendanceList = new List<WAttendance>();
		for(AggregateResult ar: [SELECT COUNT(EventId__c), UserId__r.Name FROM UserAtTheEvent__c 
												WHERE EventId__c IN :eventOfDayList GROUP BY UserId__r.Name]){
			wAttendanceList.add(new WAttendance((Integer)ar.get('expr0'),(String)ar.get('Name')));
		}
		

	}

	public class WAttendance{
		public Integer numberOfVisit {get;set;}
		public String nameStudent {get;set;}
		public WAttendance(Integer numberOfVisit, String nameStudent){
			this.numberOfVisit = numberOfVisit;
			this.nameStudent = nameStudent;
		}
	}
	
	}