src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE(Start_datetime__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finish_datetime__c</fullName>
        <label>Finish datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_datetime__c</fullName>
        <label>Start datetime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Types of events occurring during the internship.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lesson</fullName>
                <color>#0B6FCE</color>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge check</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation</fullName>
                <color>#E27001</color>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmeilSendTeachers.cls
public class EmeilSendTeachers implements Schedulable { 
	public void execute(SchedulableContext SC) {
		List<Event__c> eventToday = [SELECT Id, Teacher__c, Finish_datetime__c, 	Start_datetime__c, 	Topic__c,Type__c 
									FROM Event__c WHERE Date__c = :Date.today() AND Teacher__c != null];
		Set<Id> teachersId = new Set<Id>();
		for (Event__c currentEvent: eventToday){
			teachersId.add(currentEvent.Teacher__c);
		}
		Map<Id,User> teacherMap = new Map<Id,User>([SELECT Id, Email, Name FROM User WHERE Id IN :teachersId]);
		for (Event__c currentEvent: eventToday){
			sentEmail(teacherMap.get(currentEvent.Teacher__c), currentEvent);
		}
		



	}

	private static void sentEmail(User currentTeacher, Event__c currentEvent){		
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();  
			String[] toAddresses = new String[] {currentTeacher.Email};  
			mail.setToAddresses(toAddresses);  
			mail.setSubject('Reminder about tomorrow\'s event');  
			mail.setPlainTextBody('Dear, ' + currentTeacher.Name + ' tomorrow you are responsible for any event ' 
																 + currentEvent.Name 
																 + '. Starting at '
																 + currentEvent.Start_datetime__c.time()
																 + ', finish at '
																 + currentEvent.Finish_datetime__c.time());  
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});  
	}
}